import type { Metadata } from "next";
import type { ReactNode } from "react";
import "./globals.css";
import Navbar from "@/components/navbar/navbar";
import { Toaster } from "react-hot-toast";
import CartContextProvider from "../components/context/cartContext";
import Footer from "../components/footer/Footer";

export const metadata: Metadata = {
  title: "ShopMart App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="antialiased">
        <CartContextProvider>
          <Navbar />
          <div className="container mx-auto py-4">
            {children}
            <Toaster />
          </div>
        </CartContextProvider>
        <Footer />
      </body>
    </html>
  );
}
