import type { Metadata } from "next";
import type { ReactNode } from "react";
import "./globals.css";
import Navbar from "@/components/navbar/navbar";
import Footer from "../components/footer/Footer";
import Providers from "@/components/providers";
import MySessionProvider from "@/components/MySessionProvider/MySessionProvider";

export const metadata: Metadata = {
  title: "ShopMart App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="antialiased">
        <MySessionProvider>
          <Providers>
            <Navbar />
            <div className="container mx-auto py-4">{children}</div>
          </Providers>
          <Footer />
        </MySessionProvider>
      </body>
    </html>
  );
}
